### ISSUE TITLE
MaskedMI Code Wanted

### ISSUE THREAD

**Issue by PPBBJL** [Guanys-dar/MGDN#3]
Dear author, I can't find the code related to MaskMI in the code you uploaded. If I haven't found the code, please inform me where the code is. If it hasn't been uploaded, please upload the code. Thank you so much for your contribution!

**Comment by Guanys-dar** [comment]
Thank you for your attention.

The MI loss was introduced in the paper “Mutual Information-Driven Pan-Sharpening” (CVPR 2022). You can refer to the corresponding implementation in the following link and develop your methods:

https://github.com/manman1995/Mutual-Information-driven-Pan-sharpening/blob/5915c65f3f24ddfcf5d528d80d7b35b7f2ae9de3/models/GPPNN.py#L334

If you have any further questions, please feel free to contact me.
